/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else   /* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif  /* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif  /* __STDC__ */
#endif  /* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
//char *malloc();
//int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR unsigned char
# line 1 "lexico.l"
#define INITIAL 0
# line 2 "lexico.l"
/* Analizador de léxico */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#ifndef __STDC__
#define __STDC__
#endif
#define comentario 1
# line 19 "lexico.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;         /* input buffer */
    YY_CHAR *yy_buf_pos;        /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 78
typedef int yy_state_type;
static const short int yy_accept[239] =
    {   0,
        0,    0,   71,   71,   78,   76,   69,   68,   67,   25,
       76,   76,   76,   76,    1,    2,    5,    3,   16,    4,
        6,   27,   12,   15,   22,    7,   21,   75,   10,   11,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   13,   76,   14,   40,   71,
       73,   72,   67,   23,    0,   45,    0,    0,    0,    0,
        0,   17,    0,    0,   70,   43,   27,    0,   20,    0,
       24,   19,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   53,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   18,   71,   72,   72,   74,    0,    0,    0,   45,
        0,    0,   37,   39,   43,   38,    0,    0,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   29,   75,   75,   75,   66,   75,   75,   32,
       75,   75,   75,   75,   75,   75,   75,   44,    0,    0,
        0,    0,   33,   75,   26,   31,   75,   75,   75,   57,
       75,   75,   75,   75,   75,   75,   75,   75,   60,   75,
       75,   75,   75,   75,   34,   75,   75,   48,   75,    9,
        0,    0,    8,   28,   75,   75,   75,   46,   75,   35,
       30,   75,   75,   75,   75,   63,   75,   54,   75,   75,

       75,   64,   50,    0,    0,   58,   75,   62,   75,   75,
       59,   75,   47,   55,   36,   49,   75,   52,    0,   56,
       61,   75,   75,   42,   51,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   65,   75,   41,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   25,   39,   40,   41,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   51,
       52,   25,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    4,    5,    1,    6,    1,
        1,    1,    4,    1,    7,    1,    1,    1,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    1,    1,    1,    1
    } ;

static const short int yy_base[246] =
    {   0,
        0,    0,   54,   55,  379,  380,  380,  380,  374,  354,
       68,   26,  367,    0,  380,  380,  380,  380,  380,  359,
      361,   43,  380,  380,  109,  350,  349,    0,  380,  380,
       18,   96,  337,   87,   99,   95,  336,  104,  335,  323,
      111,   95,  325,  323,  328,  380,  310,  380,  380,    0,
      380,   53,  359,  380,  154,  380,  117,  190,  356,  327,
      318,  380,  349,  334,  380,  338,  127,  340,  380,  338,
      380,  380,    0,  311,  319,  306,  321,  316,  113,  303,
      304,  300,  306,  302,    0,  300,  108,  301,  304,  299,
      304,  301,  308,  290,  291,  297,  286,  289,  294,  293,

      292,  380,    0,  138,  146,  380,  323,  291,    0,    0,
      292,  294,  380,  380,  306,  380,  287,  306,  282,  291,
      286,  274,  288,  287,  282,  281,  267,  268,  266,  281,
      265,  275,  274,  271,  264,  257,    0,  262,  261,    0,
      264,  254,  266,  265,  255,  264,  256,  380,  289,  256,
      253,  268,    0,  252,    0,    0,  243,  241,  241,    0,
      235,  256,  251,  237,  245,  237,  236,  233,    0,  233,
      231,  242,  234,  243,    0,  241,  231,    0,  230,  380,
      216,  209,  380,    0,  218,  211,  184,    0,  185,    0,
        0,  175,  167,  167,  175,    0,  176,    0,  174,  171,

      149,    0,    0,  148,  148,    0,  133,    0,  131,  139,
        0,  142,    0,    0,    0,    0,  140,  380,  140,    0,
        0,  128,  140,    0,  380,  142,  123,  122,  130,  137,
      123,  134,  115,   95,    0,  101,    0,  380,  242,   58,
      246,  248,  255,  262,  265
    } ;

static const short int yy_def[246] =
    {   0,
      238,    1,  239,  239,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  240,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  241,  238,  238,  242,  238,  238,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  238,  238,  238,  238,  243,
      238,  244,  238,  238,   11,  238,   55,   55,   55,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  245,
      238,  238,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  238,  243,  244,  244,  238,   55,   55,   58,   55,
      238,  238,  238,  238,  238,  238,  238,  245,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  238,   55,  238,
      238,  238,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  238,
      238,  238,  238,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  238,  238,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  238,  238,  242,
      242,  242,  242,  242,  238,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,    0,  238,  238,
      238,  238,  238,  238,  238
    } ;

static const short int yy_nxt[437] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,    6,   13,   14,
       15,   16,   17,   18,   19,   20,    6,   21,   22,   23,
       24,   25,   26,   27,   28,   29,    6,   30,    6,   28,
       31,   32,   33,   34,   35,   28,   28,   36,   28,   37,
       38,   39,   28,   40,   28,   41,   42,   43,   44,   45,
       28,   28,   46,   47,   48,   49,   51,   51,   60,   66,
       74,   67,   75,   61,   63,  105,   52,   52,   55,   55,
      106,   55,   55,   56,   55,   57,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   58,   55,   59,   55,   55,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       55,   55,   55,   55,   68,   76,   80,   81,   83,   85,
      237,   69,   77,   89,  236,   86,   87,   82,   84,   97,
       78,   90,   93,   66,   94,   67,   98,  124,  107,  107,
      238,  107,  125,  132,  133,  238,  235,   95,  105,  107,
       96,   55,  107,  106,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,   55,  220,
      219,  218,  217,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,  108,  216,  109,  215,
      214,  213,  212,  211,  109,  210,  209,  208,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,   50,   50,   50,   50,   50,   50,   50,   70,
      207,  206,   70,   73,   73,  103,  205,  204,  103,  103,
      103,  103,  104,  203,  104,  104,  104,  104,  104,  118,
      118,  118,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,

      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  117,  152,  115,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  135,  134,  131,  130,  129,  128,  127,  126,  123,
      122,  121,  120,  119,  117,  116,  115,  114,  113,  112,
      111,  110,   53,  102,  101,  100,   99,   92,   91,   88,
       79,   72,   71,   65,   64,   62,   54,   53,  238,    5,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static const short int yy_chk[437] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   12,   22,
       31,   22,   31,   12,  240,   52,    3,    4,   11,   11,
       52,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   25,   32,   34,   34,   35,   36,
      236,   25,   32,   38,  234,   36,   36,   34,   35,   42,
       32,   38,   41,   67,   41,   67,   42,   79,   57,   57,
      104,   57,   79,   87,   87,  104,  233,   41,  105,   57,
       41,   55,   57,  105,  232,  231,  230,  229,  228,  227,
      226,  223,  222,  219,  217,  212,  210,  209,   55,  207,
      205,  204,  201,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,   58,  200,   58,  199,
      197,  195,  194,  193,   58,  192,  189,  187,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,  239,  239,  239,  239,  239,  239,  239,  241,
      186,  185,  241,  242,  242,  243,  182,  181,  243,  243,
      243,  243,  244,  179,  244,  244,  244,  244,  244,  245,
      245,  245,  177,  176,  174,  173,  172,  171,  170,  168,
      167,  166,  165,  164,  163,  162,  161,  159,  158,  157,
      154,  152,  151,  150,  149,  147,  146,  145,  144,  143,

      142,  141,  139,  138,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  115,  112,  111,  108,  107,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   86,   84,   83,   82,   81,   80,   78,
       77,   76,   75,   74,   70,   68,   66,   64,   63,   61,
       60,   59,   53,   47,   45,   44,   43,   40,   39,   37,
       33,   27,   26,   21,   20,   13,   10,    9,    5,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 238 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 21 "lexico.l"
return PIZ;
	YY_BREAK
case 2:
# line 22 "lexico.l"
return PDE;
	YY_BREAK
case 3:
# line 23 "lexico.l"
return SUM;
	YY_BREAK
case 4:
# line 24 "lexico.l"
return RES;
	YY_BREAK
case 5:
# line 25 "lexico.l"
return MUL;
	YY_BREAK
case 6:
# line 26 "lexico.l"
return DIV;
	YY_BREAK
case 7:
# line 27 "lexico.l"
return ASI;
	YY_BREAK
case 8:
# line 30 "lexico.l"
return CAB1;
	YY_BREAK
case 9:
# line 31 "lexico.l"
return CAB2;
	YY_BREAK
case 10:
# line 33 "lexico.l"
return CORI;
	YY_BREAK
case 11:
# line 34 "lexico.l"
return CORD;
	YY_BREAK
case 12:
# line 35 "lexico.l"
return PUNTOS;
	YY_BREAK
case 13:
# line 36 "lexico.l"
return LLIZ;
	YY_BREAK
case 14:
# line 37 "lexico.l"
return LLDE;
	YY_BREAK
case 15:
# line 38 "lexico.l"
return PYC;
	YY_BREAK
case 16:
# line 39 "lexico.l"
return COMA;
	YY_BREAK
case 17:
# line 40 "lexico.l"
return AND;
	YY_BREAK
case 18:
# line 41 "lexico.l"
return OR;
	YY_BREAK
case 19:
# line 42 "lexico.l"
return MAYORIQ;
	YY_BREAK
case 20:
# line 43 "lexico.l"
return MENORIQ;
	YY_BREAK
case 21:
# line 44 "lexico.l"
return MAYORQ;
	YY_BREAK
case 22:
# line 45 "lexico.l"
return MENORQ;
	YY_BREAK
case 23:
# line 46 "lexico.l"
return DIST;
	YY_BREAK
case 24:
# line 47 "lexico.l"
return II;
	YY_BREAK
case 25:
# line 48 "lexico.l"
return NEGEXP;
	YY_BREAK
case 26:
# line 50 "lexico.l"
return CASE;
	YY_BREAK
case 27:
# line 51 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = entero;  return NUM;}
	YY_BREAK
case 28:
# line 52 "lexico.l"
return BREAK;
	YY_BREAK
case 29:
# line 53 "lexico.l"
return INT;
	YY_BREAK
case 30:
# line 54 "lexico.l"
return FLOAT;
	YY_BREAK
case 31:
# line 55 "lexico.l"
return CHAR;
	YY_BREAK
case 32:
# line 56 "lexico.l"
return SET;
	YY_BREAK
case 33:
# line 58 "lexico.l"
return BOOL;
	YY_BREAK
case 34:
# line 59 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = booleano; return TRUE;}
	YY_BREAK
case 35:
# line 60 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = booleano; return FALSE;}
	YY_BREAK
case 36:
# line 61 "lexico.l"
return STRING;
	YY_BREAK
case 37:
# line 62 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = caracter; return CARACTER;}
	YY_BREAK
case 38:
# line 64 "lexico.l"
return ADDC;
	YY_BREAK
case 39:
# line 65 "lexico.l"
return MINC;
	YY_BREAK
case 40:
# line 66 "lexico.l"
return COMPC;
	YY_BREAK
case 41:
# line 68 "lexico.l"
return IMPRIMIR_TABLA;
	YY_BREAK
case 42:
# line 71 "lexico.l"
return TYPEDEF;
	YY_BREAK
case 43:
# line 72 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = real;  return REAL;}
	YY_BREAK
case 44:
# line 73 "lexico.l"
return OP_INOUT;
	YY_BREAK
case 45:
# line 74 "lexico.l"
{yylval.cadena = strdup(yytext); yylval.tipo = cadena; return STRING;}
	YY_BREAK
case 46:
# line 75 "lexico.l"
return EMPTY;
	YY_BREAK
case 47:
# line 76 "lexico.l"
return LENGTH;
	YY_BREAK
case 48:
# line 77 "lexico.l"
return VOID;
	YY_BREAK
case 49:
# line 78 "lexico.l"
return SWITCH;
	YY_BREAK
case 50:
# line 79 "lexico.l"
return WHILE;
	YY_BREAK
case 51:
# line 80 "lexico.l"
return INCLUDE;
	YY_BREAK
case 52:
# line 81 "lexico.l"
return DEFINE;
	YY_BREAK
case 53:
# line 82 "lexico.l"
return IF;
	YY_BREAK
case 54:
# line 83 "lexico.l"
return IN;
	YY_BREAK
case 55:
# line 84 "lexico.l"
return OUT;
	YY_BREAK
case 56:
# line 85 "lexico.l"
return DEFAULT;
	YY_BREAK
case 57:
# line 86 "lexico.l"
return ELSE;
	YY_BREAK
case 58:
# line 87 "lexico.l"
return CREATE;
	YY_BREAK
case 59:
# line 88 "lexico.l"
return INSERT;
	YY_BREAK
case 60:
# line 89 "lexico.l"
return MAIN;
	YY_BREAK
case 61:
# line 90 "lexico.l"
return EXTRACT;
	YY_BREAK
case 62:
# line 91 "lexico.l"
return DELETE;
	YY_BREAK
case 63:
# line 92 "lexico.l"
return MINUS;
	YY_BREAK
case 64:
# line 93 "lexico.l"
return UNION;
	YY_BREAK
case 65:
# line 94 "lexico.l"
return INTERSECTION;
	YY_BREAK
case 66:
# line 95 "lexico.l"
return NEG; 
	YY_BREAK
case 67:
# line 97 "lexico.l"
;
	YY_BREAK
case 68:
# line 98 "lexico.l"
linea_actual++;
	YY_BREAK
case 69:
# line 99 "lexico.l"
;
	YY_BREAK
case 70:
# line 100 "lexico.l"
{ BEGIN(comentario); }
	YY_BREAK
case 71:
# line 101 "lexico.l"

	YY_BREAK
case 72:
# line 102 "lexico.l"

	YY_BREAK
case 73:
# line 103 "lexico.l"
{++linea_actual;}
	YY_BREAK
case 74:
# line 104 "lexico.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 75:
# line 106 "lexico.l"
{ yylval.cadena = strdup(yytext); 
			         return ID;
				   }
	YY_BREAK
case 76:
# line 110 "lexico.l"
yyerror("Error en la linea: ");
	YY_BREAK
case 77:
# line 112 "lexico.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comentario):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 239 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 239 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 238);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 112 "lexico.l"

